FROM node:18

WORKDIR /app

# Copia os arquivos de dependência e instala
COPY package*.json ./
RUN npm install

# Copia o restante do projeto
COPY . .

# Expõe a porta que o Vite usa (padrão 5173)
EXPOSE 5173

# Inicia o servidor de dev do Vite
CMD ["npm", "run", "dev"]

